#!/bin/bash
# Ralph Init - Initialize Ralph in a project
#
# Creates:
#   specs/              Default specs directory
#   .ralph/             Ralph configuration and generated files
#   .ralph/config.yaml  Configuration file

set -euo pipefail

# Check if already initialized
if [ -d ".ralph" ]; then
    echo "Ralph is already initialized in this project."
    echo "Configuration: .ralph/config.yaml"
    exit 0
fi

echo "Initializing Ralph..."

# Create directories
mkdir -p specs
mkdir -p .ralph

# Create config file
cat > .ralph/config.yaml <<'EOF'
# Ralph Configuration
# See: https://github.com/eumemic/ralph

# Where to find specification files (relative to project root)
specs_dir: ./specs

# Model configuration (optional - defaults shown)
# main_model: opus
# subagent_model: sonnet
EOF

# Create spec template
cat > specs/_TEMPLATE.md <<'EOF'
# Feature: [Name]

## Overview
Brief description of what this feature does and why it exists.

## Requirements

### Functional Requirements
- [ ] Requirement 1: Description
- [ ] Requirement 2: Description

### Non-Functional Requirements
- [ ] Performance: [specific criteria]
- [ ] Security: [specific criteria]

## Acceptance Criteria
- [ ] Criterion 1: How to verify this works
- [ ] Criterion 2: How to verify this works

## Notes
Any additional context, constraints, or considerations.
EOF

# Create implementation plan placeholder
cat > .ralph/IMPLEMENTATION_PLAN.md <<'EOF'
# Implementation Plan

*This file is generated by `ralph plan`. Do not edit manually.*

Run the planning loop to generate tasks:

```bash
ralph plan
```
EOF

echo ""
echo "✓ Ralph initialized!"
echo ""
echo "Created:"
echo "  specs/                     Specification files go here"
echo "  specs/_TEMPLATE.md         Example spec format"
echo "  .ralph/config.yaml         Configuration"
echo "  .ralph/IMPLEMENTATION_PLAN.md  Task list (generated)"
echo ""
echo "Next steps:"
echo "  1. Write your first spec in specs/"
echo "     (see specs/_TEMPLATE.md for the format)"
echo ""
echo "  2. Run the planning loop:"
echo "     ralph plan"
echo ""
echo "  3. Run the building loop:"
echo "     ralph build"
