#!/bin/bash
# Ralph Init - Initialize Ralph in a project
#
# Creates:
#   specs/              Default specs directory
#   .ralph/             Ralph configuration and generated files
#   .ralph/config.yaml  Configuration file

set -euo pipefail

# Check if already initialized
if [ -d ".ralph" ]; then
    echo "Ralph is already initialized in this project."
    echo "Configuration: .ralph/config.yaml"
    exit 0
fi

echo "Initializing Ralph..."

# Create directories
mkdir -p specs
mkdir -p .ralph

# Create config file
cat > .ralph/config.yaml <<'EOF'
# Ralph Configuration
# See: https://github.com/eumemic/ralph

# Where to find specification files (relative to project root)
specs_dir: ./specs

# Shared utilities directory (for code reuse steering)
shared_utils_dir: ./src/lib

# Git automation (uncomment to enable)
# auto_push: true
# auto_tag: true
EOF

# Create implementation plan placeholder
cat > .ralph/IMPLEMENTATION_PLAN.md <<'EOF'
# Implementation Plan

*This file is generated by `ralph plan`. Do not edit manually.*

Run the planning loop to generate tasks:

```bash
ralph plan
```
EOF

# Create AGENTS.md for operational knowledge
cat > .ralph/AGENTS.md <<'EOF'
## Build & Run

Succinct rules for how to BUILD the project:

## Validation

Run these after implementing to get immediate feedback:

- Tests: `[test command]`
- Typecheck: `[typecheck command]`
- Lint: `[lint command]`

## Operational Notes

Succinct learnings about how to RUN the project:

### Codebase Patterns

EOF

echo ""
echo "✓ Ralph initialized!"
echo ""
echo "Created:"
echo "  specs/                          Specification files go here"
echo "  .ralph/config.yaml              Configuration"
echo "  .ralph/IMPLEMENTATION_PLAN.md   Task list (generated)"
echo "  .ralph/AGENTS.md                Operational knowledge"
echo ""
echo "Next steps:"
echo "  1. Edit .ralph/AGENTS.md with your build/test commands"
echo ""
echo "  2. Write your first spec in specs/"
echo ""
echo "  3. Run the planning loop:"
echo "     ralph plan"
echo ""
echo "  4. Run the building loop:"
echo "     ralph build"
